server:
  port: 9090

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/user/**
          filters:
#            - JwtAuthenticationGatewayFilterFactory
      discovery:
        locator:
          enabled: true
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
