server:
  port: 9090

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: USERMANAGEMENT
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

  main:
    web-application-type: reactive
